// Generated by gencpp from file my_stepper_package/StepperPosition.msg
// DO NOT EDIT!


#ifndef MY_STEPPER_PACKAGE_MESSAGE_STEPPERPOSITION_H
#define MY_STEPPER_PACKAGE_MESSAGE_STEPPERPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_stepper_package
{
template <class ContainerAllocator>
struct StepperPosition_
{
  typedef StepperPosition_<ContainerAllocator> Type;

  StepperPosition_()
    : target_position(0)  {
    }
  StepperPosition_(const ContainerAllocator& _alloc)
    : target_position(0)  {
  (void)_alloc;
    }



   typedef int32_t _target_position_type;
  _target_position_type target_position;





  typedef boost::shared_ptr< ::my_stepper_package::StepperPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_stepper_package::StepperPosition_<ContainerAllocator> const> ConstPtr;

}; // struct StepperPosition_

typedef ::my_stepper_package::StepperPosition_<std::allocator<void> > StepperPosition;

typedef boost::shared_ptr< ::my_stepper_package::StepperPosition > StepperPositionPtr;
typedef boost::shared_ptr< ::my_stepper_package::StepperPosition const> StepperPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_stepper_package::StepperPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_stepper_package::StepperPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_stepper_package::StepperPosition_<ContainerAllocator1> & lhs, const ::my_stepper_package::StepperPosition_<ContainerAllocator2> & rhs)
{
  return lhs.target_position == rhs.target_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_stepper_package::StepperPosition_<ContainerAllocator1> & lhs, const ::my_stepper_package::StepperPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_stepper_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_stepper_package::StepperPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_stepper_package::StepperPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_stepper_package::StepperPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_stepper_package::StepperPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_stepper_package::StepperPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_stepper_package::StepperPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_stepper_package::StepperPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6a1d1aa0ffbed71ad4b001fb7a4d9c9";
  }

  static const char* value(const ::my_stepper_package::StepperPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6a1d1aa0ffbed71ULL;
  static const uint64_t static_value2 = 0xad4b001fb7a4d9c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_stepper_package::StepperPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_stepper_package/StepperPosition";
  }

  static const char* value(const ::my_stepper_package::StepperPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_stepper_package::StepperPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 target_position\n"
"\n"
;
  }

  static const char* value(const ::my_stepper_package::StepperPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_stepper_package::StepperPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepperPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_stepper_package::StepperPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_stepper_package::StepperPosition_<ContainerAllocator>& v)
  {
    s << indent << "target_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_STEPPER_PACKAGE_MESSAGE_STEPPERPOSITION_H
